### ISSUE TITLE
Possible thing compatibility with isy 5.0

### ISSUE THREAD

**Issue by ve7gel** [QuailAutomation/openhab2-addons#10]
Craig, as requested.
An 'ON' command from any UI generates this output in the Karaf console

`15:39:23.507 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - handle command, channel: isy:switch:f75c62c0:2A_40_99:state, command: ON
15:39:23.508 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - insteon address for command is: 2A 40 99 1
15:39:23.509 [DEBUG] [b.binding.isy.internal.IsyRestClient] - changeNodeState called, command: DON, value: 0, address: 2A 40 99 1
15:39:23.531 [INFO ] [marthome.event.ItemStateChangedEvent] - isy_Upper_Hall_Master changed from OFF to ON
15:39:23.556 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1761" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo>[INST-TX-I1  ] 02 62 2A 40 99 0F 13 00</eventInfo></Event>
15:39:23.578 [DEBUG] [b.binding.isy.internal.IsyRestClient] - Result of call: InboundJaxrsResponse{context=ClientResponse{method=GET, uri=http://192.168.155.50/rest/nodes/2A%2040%2099%201/cmd/DON/0, status=200, reason=OK}} 
15:39:23.581 [DEBUG] [b.binding.isy.internal.IsyRestClient] - Result status:  200
15:39:23.582 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - result: true
15:39:23.588 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:39:23.594 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'isy_Upper_Hall_Master' received command ON
15:39:23.598 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1762" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo>[INST-ACK    ] 02 62 2A.40.99 0F 13 00 06          LTOFFRR(00)</eventInfo></Event>
15:39:23.616 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:39:23.875 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1763" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo>[INST-SRX    ] 02 50 2A.40.99 2B.95.48 2B 13 00    LTOFFRR(00)</eventInfo></Event>
15:39:23.922 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:39:23.930 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1764" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo><![CDATA[[Std-Direct Ack] 2A.40.99-->ISY/PLM Group=0, Max Hops=3, Hops Left=2]]></eventInfo></Event>
15:39:23.953 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node:N`

and this output in the isy event viewer:

'Wed 06/07/2017 03:23:38 PM : [INST-TX-I1  ] 02 62 2A 40 99 0F 13 00
Wed 06/07/2017 03:23:38 PM : [INST-ACK    ] 02 62 2A.40.99 0F 13 00 06          LTOFFRR(00)
Wed 06/07/2017 03:23:38 PM : [INST-SRX    ] 02 50 2A.40.99 2B.95.48 2B 13 00    LTOFFRR(00)
Wed 06/07/2017 03:23:38 PM : [Std-Direct Ack] 2A.40.99-->ISY/PLM Group=0, Max Hops=3, Hops Left=2
Wed 06/07/2017 03:23:45 PM : [INST-TX-I1  ] 02 62 2A 40 99 0F 13 00
Wed 06/07/2017 03:23:45 PM : [INST-ACK    ] 02 62 2A.40.99 0F 13 00 06          LTOFFRR(00)
Wed 06/07/2017 03:23:46 PM : [INST-SRX    ] 02 50 2A.40.99 2B.95.48 2B 13 00    LTOFFRR(00)
Wed 06/07/2017 03:23:46 PM : [Std-Direct Ack] 2A.40.99-->ISY/PLM Group=0, Max Hops=3, Hops Left=2'

An "OFF"command has this log output:

`15:42:58.215 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - handle command, channel: isy:switch:f75c62c0:2A_40_99:state, command: OFF
15:42:58.219 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - insteon address for command is: 2A 40 99 1
15:42:58.223 [DEBUG] [b.binding.isy.internal.IsyRestClient] - changeNodeState called, command: DOF, value: 0, address: 2A 40 99 1
15:42:58.228 [INFO ] [marthome.event.ItemStateChangedEvent] - isy_Upper_Hall_Master changed from ON to OFF
15:42:58.269 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1992" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo>[INST-TX-I1  ] 02 62 2A 40 99 0F 13 00</eventInfo></Event>
15:42:58.277 [DEBUG] [b.binding.isy.internal.IsyRestClient] - Result of call: InboundJaxrsResponse{context=ClientResponse{method=GET, uri=http://192.168.155.50/rest/nodes/2A%2040%2099%201/cmd/DOF/0, status=200, reason=OK}} 
15:42:58.278 [DEBUG] [b.binding.isy.internal.IsyRestClient] - Result status:  200
15:42:58.280 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'isy_Upper_Hall_Master' received command OFF
15:42:58.332 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:42:58.334 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1993" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo>[INST-ACK    ] 02 62 2A.40.99 0F 13 00 06          LTOFFRR(00)</eventInfo></Event>
15:42:58.351 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:42:58.590 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1994" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo>[INST-SRX    ] 02 50 2A.40.99 2B.95.48 2B 13 00    LTOFFRR(00)</eventInfo></Event>
15:42:58.612 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:42:58.613 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1995" sid="uuid:1951"><control>_7</control><action>1</action><node></node><eventInfo><![CDATA[[Std-Direct Ack] 2A.40.99-->ISY/PLM Group=0, Max Hops=3, Hops Left=2]]></eventInfo></Event>
15:42:58.630 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _7, Action: 1, Node: 
15:42:58.663 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: <?xml version="1.0"?><Event seqnum="1996" sid="uuid:1951"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
15:42:58.679 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Control: _0, Action: 120, Node:`

and this output in the isy event viewer:

`Wed 06/07/2017 03:42:58 PM : [INST-TX-I1  ] 02 62 2A 40 99 0F 13 00
Wed 06/07/2017 03:42:58 PM : [INST-ACK    ] 02 62 2A.40.99 0F 13 00 06          LTOFFRR(00)
Wed 06/07/2017 03:42:58 PM : [INST-SRX    ] 02 50 2A.40.99 2B.95.48 2B 13 00    LTOFFRR(00)
Wed 06/07/2017 03:42:58 PM : [Std-Direct Ack] 2A.40.99-->ISY/PLM Group=0, Max Hops=3, Hops Left=2`

Let me know if you need anything else.

Cheers,
Gordon

**Comment by craigham** [comment]
do you have any insteon dimmers?  If so, could you turn one on with a slider?   Or maybe from Karaf 

smarthome:update <item> 230

Insteon is 0 - 255 for value.

**Comment by craigham** [comment]
I see the rest call for nodes is sending /DON/0....but the documentation I am reading now states DON/xx sets it on to the xx level.  I am away from my isy right now, so hard for me to test.  I will keep investigating.

**Comment by craigham** [comment]
could you try dropping this jar into your addons folder and see if it addresses the issue.  I'll apologize in advance if there is a silly bug, I don't have access to my isy from where I am at.

https://s3-us-west-2.amazonaws.com/craigham-pub/org.openhab.binding.isy-fix-DON-2.1.0-SNAPSHOT.jar

**Comment by ve7gel** [comment]
Sorry Craig, no change.  I still see the DON/0 and the same sequence in the isy event viewer.  Just to confirm I've got the right jar loaded:
`Bundle-Name = Isy Binding
Bundle-RequiredExecutionEnvironment = JavaSE-1.7
Bundle-SymbolicName = org.openhab.binding.isy;singleton:=true
Bundle-Vendor = openHAB
Bundle-Version = 2.1.0.201706071652`

The dimmers work fine BTW.

**Comment by craigham** [comment]
that may be the incorrect jar.  You may not have noticed, but I made a special jar just for this issue, the filename includes fix-DON....it was built at the 16 minute mark, and looking at the version you specified above it is showing the 52 minute mark, which was the earlier build, with the standard name.  could you make sure you remove the old jars for this binding and try that last one?

**Comment by ve7gel** [comment]
Looks like that was the fix.  I had some issue removing the old bundle and getting this one running in its place, but it all looks good now.  I re-downloaded your build from the link above, and the version is now 2.1.0.201706080013.

Thanks a bunch for your work on this and your response!
