### ISSUE TITLE
Aux Temp Sensor High Setpoint missing

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#102]
Aux temp sensor high setpoint is not an available channel.  Low setpoint works.

**Comment by boc-tothefuture** [comment]
Low was actually broken too (It was broken in jomnilink).

**Comment by swamiller** [comment]
Looks good to me, thank you!

**Comment by boc-tothefuture** [comment]
@craigham I think we can close this now.
