### ISSUE TITLE
Capture User Actions from Omni log file

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#112]
I am trying to pass usernames to a notification app (Pushover) during alarm mode changes (arm away, disarm, arm night, etc.).  I have a map file with code to name translations. One problem I have is the omnilink binding doesn't seem to capture codes entered at a console.  I am able to pass user codes within OH (programmed from a rule and human readable) and map the code to the user. The problem with this method is the binding is sending two responses, one with the code sent and a second "UNDEF" user (state). 

**Test Rule:**
rule "Pushover Notification Alarm Set"
when
	Item AlarmMode changed
then
       val vAlarmMode = transform("MAP","area-modes.map",(AlarmMode.state).toString)
       val vWho = transform("MAP","usercode.map", AlarmModeDisarm.state.toString)
	val message="Alarm set to: " + vAlarmMode + " by " + vWho
	pushover(message)
	logInfo("Alarm Message",AlarmModeDisarm.toString)
end

**Output from OH Log:**
2017-11-22 01:53:45.181 [INFO ] [.smarthome.model.script.Item Trigger] - Steve
2017-11-22 01:53:45.617 [INFO ] [.smarthome.model.script.Item Trigger] - Unknown

**Event log from PC Access:**
5	11/21 7:53 PM	Steve DISARM House Area
6	11/21 7:52 PM	Steve ARM House Area DAY

The Event logs from the Omni accurately show who sent an action regardless if sent from a rule or manually entered at the console.

Is it possible to read the omni event log and capture usable data to trigger rules?  This would be advantageous from a security standpoint because user codes would not need to be made visible within OH because the translation from code to username would happen within the omni panel. 

If not, is there an intended way to handle capturing user codes used for alarm actions?

**Comment by boc-tothefuture** [comment]
Looking at the protocol - omni does not appear to send the user code during an area event.  We can access the log. However, Omni doesn't send a notification when something is written to the log. We would need to implement some sort of polling mechanism.

I am also not sure how we would represent a log in OpenHab?  Its an array of strings - what does that map to in omni? One large string?

**Comment by swamiller** [comment]
I wonder if using the protocol similar to the Onkyo Binding might work.  More specifically, the Onkyo Binding somehow "polls" the receiver's list of Net stations (Pandora as an example) and assigns them to items. 

From the Onkyo Binding:
netmenu#item0 through netmenu#item9
These are each string items with one line of data.  

If we could do something similar with the omni log data and only capture the last "x" number of lines and assign each to a preset number item.  That might allow using the item data for rules...maybe?

The other would be to see if one of the current omnilink items is sending the user code data.

**Comment by BCS-JonW** [comment]
None of the Omnilink "unsolicited event" items sends a user code.  That data only comes from the log.

You wouldn't need to do period polling of the log if you're just looking for who performed the last user action.  Seems you could just poll the log on demand when OpenHAB gets unsolicited events for access control, zone bypass/restore or area armed/disarmed.  Those are really the only time you need to know who performed the action and that would be written to the log at the same time you get the notification of the event.

You can poll for most recent event, then step backwards through them until you get to the one you're looking for (e.g. area mode change).  In most cases, the latest log entry would probably be the one you're looking for, so you'd get your user ID with just one request.  Worst case it would only be a few records back in the log buffer.

**Comment by boc-tothefuture** [comment]
Ok.  Last week I pushed the audio source stuff out.  That is also polling based so we have a framework for polling style updates in this binding now.

The lack of any sort of list type in OpenHAB really ties our hands here from an architecture perspective.

Should we only have an item for the last log line?  If you want more you persist them in OpenHAB rules?  Or is the last 10 better for some reason?


@craigham you have an opinion?

**Comment by craigham** [comment]
I really don't have much to add on this.  utilizing persistence seems like
a reasonable place to start as it keeps the binding a little simpler I
would say, presumably at the expense of rules which would have to fish out
previous values.

**Comment by boc-tothefuture** [comment]
@swamiller and @BCS-JonW - 
  I looked at this a bit more w/ the API doc in front of me.  Items are not returned as a log of text, rather as 2 or 3 distinct fields in a message.  This complicates matters a little bit.  My initial plan was to just have the last 'message' in a channel that could be accessed.  But if I need three channels this becomes very complicated because the states may not match up based on when the rule processes the channel update.  This to me means we need to store the entire 'message' as a single channel.  In order to do this, I am going to recommend the channel contains JSON.  This is something the russound binding does as well.

You OK with processing JSON in the rules?

**Comment by boc-tothefuture** [comment]
@swamiller - PR #122 has initial support for event log messages.  Can you validate this works for your use cases?

**Comment by swamiller** [comment]
@boc-tothefuture - will this show up as an item?  I added the latest binding, deleted cache/tmp files and reloaded and no new items.  I checked the OH log as well and didn't see any omnipro messages there either.

How is this function to be used?

**Comment by boc-tothefuture** [comment]
It is just be a new channel on the bridge itself. Name of the channel is "last_log".

**Comment by swamiller** [comment]
Ok, I see.  The "last_log" channel isn't showing up.  Consequently, the other added channels are greyed out as well.

![image](https://user-images.githubusercontent.com/17254439/34019059-a04d14dc-e0f2-11e7-88f1-06c730a7b0f6.png)

**Comment by boc-tothefuture** [comment]
@swamiller -
  Are you sure you have the latest after the PR was merged by @craigham ?

Here is how it looks on my system:
![image](https://user-images.githubusercontent.com/13153815/34023144-47421a9e-e111-11e7-8f03-761aa5de18b8.png)

**Comment by swamiller** [comment]
I deleted my json database and restarted OH and i have the channel now. 
How do I decipher the data?  I recognize the date/time but the other data is cryptic. I don't see anything that I can relate back to a user.  Here is a screenshot of my phone app that directly reads the omnipro event file:
![image](https://user-images.githubusercontent.com/17254439/34024444-c2aa40f0-e10f-11e7-86d3-b3ea9794b5d2.png)

**Comment by boc-tothefuture** [comment]
Right now we are just reporting the raw message from the omnipro - not doing any translations which your app is doing.  

> The event, parameter 1, and parameter 2 identify the specific event that has occurred. The possible events are shown in the “Event Log Event Types” tables. When a security code is specified, the value is the user code number rather than the actual four-digit security code.
In addition to the user codes, the following security codes can be reported:
251 Duress code
252 Keyswitch
253 Quick arm
254 PC Access
255 Programmed


Event Type | Parameter 1 P1 | Parameter 2 P2 | Description
-- | -- | -- | --
4 | 1-n | 1-n | zone P2 bypassed with code P1
5 | 1-n | 1-n | zone P2 restored with code P1
6 | 1-n | 0-n | all area P2 zones restored with code P1 P2 = 0 means all areas/zones
48+m | 1-n | 0-n | area P2 armed in mode m with code P1 P2 = 0 means all areas m = security mode: 0 = disarm  								1 = day mode 2 = night mode 3 = away mode 4 = vacation mode 5 = day instant mode 6 = night delayed mode
128 |   | 1-n | zone P2 tripped
129 |   | 1-n | zone P2 trouble
130 | 1-n |   | remote phone access with code P1
131 |   |   | remote phone lockout
132 |   | 1-n | zone P2 auto bypassed
133 |   | 1-n | zone P2 trouble cleared
134 | 1-n |   | PC access with code P1
135 | 1-n | 1-n | alarm P1 activated in area P2 1 = burglary 2 = fire 3 = gas  								4 = auxiliary 5 = freeze 6 = water 7 = duress  								8 = temperature
136 | 1-n | 1-n | alarm P1 reset in area P2 1 = burglary 2 = fire 3 = gas  								4 = auxiliary 5 = freeze 6 = water 7 = duress  								8 = temperature
137 |   |   | system reset
138 |   | 1-n | message P2 logged
139 |   | 1-n | zone P2 shut down
140 | 1-n | 1-n | access granted to user P1 at reader P2
141 | 1-n | 1-n | access denied to user P1 at reader P2

**Comment by swamiller** [comment]
Ok, I get it...nothing is simple with HAI!  Thank you for this enhancement!  I like this path much better than exposing user codes in OH.

**Comment by boc-tothefuture** [comment]
Let me know when you get a chance to test it out so we can close this issue or fix any bugs that come up.

Thanks!

**Comment by boc-tothefuture** [comment]
@swamiller - have you been able to test this yet?

**Comment by swamiller** [comment]
Sorry for the delay, yes I am consistently getting the last log file message.  This request can be closed, however, is there hope of having the binding do the translations in the future?

**Comment by boc-tothefuture** [comment]
Yeah - Feel free to add another issue for that because we would have to discuss how that would look.
@craigham  I think you can close this.

**Comment by swamiller** [comment]
@boc-tothefuture I got this working and thought I would share what I did.  Please note I'm sure there arem more efficient ways to do program this but this was my amateur attempt. 

I used the Omni-Link protocol to figure out the code mappings for the Event Types, User numbers, and Parameter 2 (which is has been assigned several tasks).  I used the JSONPATH transformation to read the log file and MAP transformation and 3 different MAP files to translate the codes from the log file to usable information.

I then combine the translated data to a string message and send to my cell phone via Pushover.  I'm very happy!  This replaced a now defunct notification system I was using and enhanced it a bit by adding specific user names to the notifications. 

**LastLog reader rule:**
rule "Read Log and Notify"
when
    Item LastLog received update
then
    val json = LastLog.state.toString
    val tempUser = transform("JSONPATH", "$.parameter1", json)
    val tempEvent = transform("JSONPATH", "$.eventType", json)
    val tempParam2 = transform("JSONPATH", "$.parameter2", json)
    val vUser = transform("MAP","usercode.map", tempUser)
    val vEvent = transform("MAP","omnieventcode.map", tempEvent)
    //val vParam2 = tempParam2
  if (tempEvent == "105" || tempEvent == "106") {
      val vParam2 = transform("MAP","door.map",tempParam2) 
      postUpdate(Param2, vParam2)     
    } else {
      val vParam2 = transform("MAP","omnieventcode.map",tempParam2)
      postUpdate(Param2, vParam2)
    }
    val message=Param2.state.toString + " " + vEvent + " by " + vUser
    logInfo("Log", Param2.state.toString + " " + vEvent + " by " + vUser)
    postUpdate(LastUser, vUser) 
    postUpdate(LogEvent, vEvent)    
    pushover(message)
end

**omnieventcode.map** - numerical "Event Type" code translations from Omni-Link Protocol (except code 1 and 2 which are being used by Parameter2 for Area names)

1=HOUSE
2=OUTSIDE
4=ZONE BYPASSED
5=ZONE RESTORED
6=ALL ZONES RESTORED
48=Alarm set to DISARM
49=Alarm set to DAY
50=Alarm set to NIGHT
51=Alarm set to AWAY
52=Alarm set to VACATION
53=Alarm set to DAY INSTANT
54=Alarm set to NIGHT DELAYED
105=DOOR LOCKED
106=DOOR UNLOCKED
128=ZONE TRIPPED
129=ZONE TROUBLE
130=REMOTE PHONE ACCESS
131=REMOTE PHONE LOCKOUT
132=ZONE AUTO BYPASSED
133=ZONE TROUBLE CLEARED
134=PC ACCESS
135=ALARM ACTIVATED
136=ALARM RESET
137=SYSTEM RESET
138=MESSAGE LOGGED
139=ZONE SHUT DOWN
140=ACCESS GRANTED
141=ACCESS DENIED

**door.map** - Lock Numbers from PC Access - Parameter2
1=FRONT
2=BACK
3=GARAGE ENTRY

**usercode.map** - User Code positions to user names from PC Access - Parameter1
0=Unknown
1=SERVICE CODE
2=Name of user 2
3=Name of user 3
4=Name of user 4
5=Name of user 5
6=Name of user 6
7=Name of user 7
8=Name of user 8
9=openHAB
255=SYSTEM
Unknown=Unknown
