### ISSUE TITLE
Duplicate Temperature and Humidity Things discovered

### ISSUE THREAD

**Issue by BCS-JonW** [QuailAutomation/openhab2-addons#113]
Since the added support for Temperature and Humidity Auxilliary zones, the discovery process now finds and adds the temperature and humidity zones twice.  They are added once as aux sensors and added again as zones.

Seems that discovery should only add them as the aux type and not a zone.

![hai_temp_humi_dups](https://user-images.githubusercontent.com/7365166/33627874-bbe4f34a-d9b3-11e7-9245-4cad7faa13cb.PNG)

Additionally, the item definitions do not allow the use of a specified controller ID in the channel definition.
{channel="omnilink:temp_sensor:14:temperature"}
{channel="omnilink:humidity_sensor:15:humidity"}

All other item channel definitions all specify the controller ID.
e.g. Zone, UPB, Flags, Buttons, etc. all use the controller within the channel id:
{channel="omnilink:zone:home:1:contact"}
{channel="omnilink:upb:home:2:level"}
{channel="omnilink:button:home:1:press", autoupdate="false"}
{channel="omnilink:flag:home:397:switch"}

**Comment by boc-tothefuture** [comment]
Didn't see this till now - I can take a look.

**Comment by boc-tothefuture** [comment]
@BCS-JonW - Can you validate the latest version of the binding doesn't have this issue?

**Comment by BCS-JonW** [comment]
Correct.  It no longer adds temp/humidity zones as security zones.  Also now uses the controller ID designation in the items file as it should.

On a related note though, the thermostat definitions still do not allow the controller ID to be added to the item definition.  (I know, that should have been reported when thermostats were being worked on, but it is the same related issue that the temp/humidity sensors had).

**Comment by boc-tothefuture** [comment]
@craigham - I think this can be closed now.

**Comment by boc-tothefuture** [comment]
@craigham - can you close this?

**Comment by boc-tothefuture** [comment]
@craigham - bump on closing this.
