### ISSUE TITLE
Device type : 02.16

### ISSUE THREAD

**Issue by samroy** [QuailAutomation/openhab2-addons#116]
Hello :)
I very like this isy addon. Thank you very much !!!

All my devices has been recognized except those of type **02.16 (2876SB) [ICON IN-WALL ON/OFF SWITCH]**. They are discontinued but I still got some here in my home.

So, May I suggest adding this line 
`mMapDeviceTypeThingType.put("02.16", IsyBindingConstants.SWITCH_THING_TYPE);`
to IsyRestDiscoveryService.java ?

Thanks again,
Sam.

**Comment by craigham** [comment]
latest build should discover that device now.
