### ISSUE TITLE
Omnilink binding doesn't support generic units

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#121]
Please add support for unit type of output.

**Comment by 2MuchTech** [comment]
A little more background on this...  I have been using openHAB 1 with the original omnilink binding, and it understands what a "unit" is.  My "items" all end in something like {omnilink="unit:12"} and openHAB 1 has no problem controlling the lights.  In PC Access each unit is of type "Vizia RF Z-Wave".

In openHAB 2.1 with the marketplace omnilink binding it never even discovers any of my units.  If I manually add a Thing and tell it to use "unit" as the type, PaperUI never gives me an opportunity to make a Bridge Selection.  If I tell it it's a UPB unit, then I do see the Bridge Selection and I can assign one of my items that OH2 has pulled in from the default.items file that I copied from my openHab 1 installation, but controlling the light seems a little wonky from the very limited testing I did last night.

Thanks.

**Comment by craigham** [comment]
@2MuchTech Issues with that type of light don't surprise me.  

Up to this point I believe the rest of the users have just been using upb.

Not sure how this can be tackled unless we have someone with such lights hooked up.  @2MuchTech do you have the ability to try and implement vizia lights?  Or no?

**Comment by BCS-JonW** [comment]
I have both UPB and Vizia defined on my system.  OpenHAB never discovers the Vizia devices.  As a work-around, I temporarily defined them as UPB within PC Access, downloaded to the panel, then ran discovery to get them setup as Things.  Once setup on OpenHAB, I changed them back to Vizia and again downloaded to reset the panel.  Those devices are now represented in OpenHAB as UPB, but are controlled as normal units.

The API call to the OmniPro just controls a "Unit", so theoretically, any defined unit should be imported into OpenHAB, regardless of their type.  If they're not UPB, they should just be added as a generic "Unit".

**Comment by 2MuchTech** [comment]
@craigham I've got plenty of Vizia RF+ devices in my system (switches, dimmers, 4 button scene controllers, 4 button on/off controllers).  If you're asking whether I can test code to see if it works, absolutely!  If you're asking if I have the ability to dive into the code to see if I can fix it, I'm not sure.  I can take a look at it, but I no longer write code on a regular basis, so it will likely take me some time to figure out what I'm looking at.

**Comment by boc-tothefuture** [comment]
FYI - I had started this particular issue for missing unit type output (not generic units).  But there is good conversation in here so I retitled and will open another one just for Output type units.

**Comment by mattlapine** [comment]
Searching thru the community forum led me to this issue.  I see this is still open, so presumably generic unit support was never added in the binding, but UPB units work, thus the workaround is to use UPB for now?

**Comment by boc-tothefuture** [comment]
Generic unit support was added in #142 
I am going to close this issue to prevent future confusion.  
@mattlapine - Can you open a separate issue if it isn't working for you?
