### ISSUE TITLE
Thermostats don't report controller ID

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#123]
Per comment in #113 

> On a related note though, the thermostat definitions still do not allow the controller ID to be added to the item definition. (I know, that should have been reported when thermostats were being worked on, but it is the same related issue that the temp/humidity sensors had).

**Comment by BCS-JonW** [comment]
Just as a point of illustration, see attached pic that demonstrates the missing controller within Thing definitions.
![hai_themostat_no_controller](https://user-images.githubusercontent.com/7365166/34012166-9045a80e-e0c7-11e7-901d-e49c97bfa78f.PNG)

**Comment by BCS-JonW** [comment]
This looks to be fixed now. Thanks.

**Comment by boc-tothefuture** [comment]
Closing.  Fixed by #125
