### ISSUE TITLE
BaseThingHandler.initialize() will be removed soon

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#128]
I am getting the following error repeatedly during restart:

`2018-03-31 22:06:04.387 [WARN ] [.core.thing.binding.BaseThingHandler] - BaseThingHandler.initialize() will be removed soon, ThingStatus can be set manually via updateStatus(ThingStatus.ONLINE)`

The message seems associated with ominlink thing status updates during restart.

**Comment by craigham** [comment]
yes, there is a call to a inherited method around initialize that has been deprecated in openhab.  Someone will have to remove that call.

**Comment by boc-tothefuture** [comment]
@craigham I am doing a few things in OpenHab.  My time will be limited, but I may be able to make some progress here and there.  What version of OpenHab are we currently targeting?  I am currently on 2.2, have we tested this driver on 2.3?

**Comment by craigham** [comment]
@boc-tothefuture which version of openhab is a good question.  About a month ago I tried to get the repository caught up to openhab/openhab and didn't get very far, and gave up.  

I think ideally we want the branch current to the latest master.  I'm not sure if we have to squash all the commits first and rebase, or what.  Have gotten out of my comfort zone with git unfortunately.

What do you think?

**Comment by swamiller** [comment]
Looks like this one is fixed.
