### ISSUE TITLE
Unable to send UPB Scene command

### ISSUE THREAD

**Issue by jmActifio** [QuailAutomation/openhab2-addons#133]
First, to all of those who created and maintain the new version of the OmniLink binding, a huge thank you!  I have a large OmniPro system with multiple expansion modules and enclosures representing years of work and sweat, and this finally lets me migrate up to OpenHAB 2.

In the original v1 binding one could define a UPB device as such:
String	DeckLight_String	"Deck [%s]"	(Lights_Deck)	{omnilink="unit:49"}

And then in a rule:
sendCommand(DeckLight_String, 'scene a')

Attempting this against the 'upb Thing' object fails.  Is there a way to do this with the new binding?

**Comment by boc-tothefuture** [comment]
This is probably better handled in the support forum, so others can see the question and pitch in with an answer.  https://community.openhab.org/t/hai-omnilink-binding-for-openhab-2-0/21049/41

Taking a quick look, scenes are now channels of type switch belonging to a think room.  So you would be sending an ON type to the appropriate channel "scene_a" for example, of the room thing.

**Comment by boc-tothefuture** [comment]
@jmActifio can I close this?
