### ISSUE TITLE
Omni All On/Off (Button 4 1 /4 0 needs a channel)

### ISSUE THREAD

**Issue by mjcumming** [QuailAutomation/openhab2-addons#134]
Currently the all on/off commands from a Omni console generate this event

`2018-11-01 08:33:38.408 [vent.ChannelTriggeredEvent] - omnilink:area:9ffcfafd:1:all_on_off_Event triggered OFF`

which is not mappable to an item using a channel.

**Comment by boc-tothefuture** [comment]
I will try and take a look at this over the holiday break.

**Comment by boc-tothefuture** [comment]
@mjcumming - are you saying you want to detect when an all on/off event happens?  Or you want to trigger the all on/off event on the omni?

**Comment by mjcumming** [comment]
The Omni 4-0 and 4-1 All On/Off button presses from the console. Its the system event ALL ON/OFF 0000 0011 111s aaaa s = state

**Comment by boc-tothefuture** [comment]
Ah, ok.. So  that would be a trigger channel then.  I am looking at some more of those for UPB links, so I can add it at the same time.

**Comment by boc-tothefuture** [comment]
@mjcumming - 
  I started looking at this.  It is a channel trigger (there is no state) so it should not be mapped to an item. It should be processed in your rules as other channel triggers would.

**Comment by mjcumming** [comment]
I do see the channel event, didn't realize you can't map that to an item and that you must create a rule to get the channel event - thank you.

2018-11-01 08:33:38.408 [vent.ChannelTriggeredEvent] - omnilink:area:9ffcfafd:1:all_on_off_Event triggered OFF
