### ISSUE TITLE
zones decimal, or string for channels

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#14]
There is a type mismatch in the zones, string or number.

getting this in logs:

`2017-06-11 19:11:32.369 [DEBUG] [s.c.internal.items.ItemUpdater:72   ] - Received update of a not accepted type (DecimalType) for item omnilink_zone_2_current_condition
2017-06-11 19:11:32.369 [INFO ] [smarthome.event.ItemStateEvent:43   ] - omnilink_zone_2_current_condition updated to 0
2017-06-11 19:11:32.370 [DEBUG] [s.c.internal.items.ItemUpdater:72   ] - Received update of a not accepted type (DecimalType) for item omnilink_zone_2_latched_alarm_status
2017-06-11 19:11:32.370 [INFO ] [smarthome.event.ItemStateEvent:43   ] - omnilink_zone_2_latched_alarm_status updated to 0
2017-06-11 19:11:32.371 [DEBUG] [s.c.internal.items.ItemUpdater:72   ] - Received update of a not accepted type (DecimalType) for item omnilink_zone_2_arming_status
`

Here is the code (using decimal type):

`updateState(OmnilinkBindingConstants.CHANNEL_ZONE_CONTACT, contactState);
		updateState(OmnilinkBindingConstants.CHANNEL_ZONE_CURRENT_CONDITION, new DecimalType(current));
		updateState(OmnilinkBindingConstants.CHANNEL_ZONE_LATCHED_ALARM_STATUS, new DecimalType(latched));
		updateState(OmnilinkBindingConstants.CHANNEL_ZONE_ARMING_STATUS, new `DecimalType(arming));``

Here is the xml for one of the channels (expecting strings):

`<channel-type id="zone_latched_alarm_status">
		<item-type>String</item-type>
		<label>Latched Alarm Status</label>
		<description>Latched alarm status of a zone.</description>
		<category>Contact</category>
		<state pattern="%s" readOnly="true">
			<options>
				<option value="Secure">Secure</option>
				<option value="Tripped">Tripped</option>
				<option value="Reset">Reset, but previously tripped</option>
			</options>
		</state>
	</channel-type>`

**Comment by digitaldan** [comment]
Yes, I saw this too.  Whats strange is that it was working!   I'll take a look to see what I broke :-)

**Comment by digitaldan** [comment]
So I'm not sure if this something left over in the system since we have changed the thing types, or a class loading issue. But I uninstalled the binding, restarted OH and installed the binding, and now I'm not seeing the issue anymore.

**Comment by craigham** [comment]
when you say installed the binding, how are you doing that?  I am getting these errors when I run in eclipse debug mode.  

And what is the intention, a String or a number?

**Comment by craigham** [comment]
I'm confused.

The channels.xml for the zone channels defines it as a string, and the code uses DecimalType.  I'm confused how this could work, unless you are expecting some implicit conversion from the DecimalType to a String.

**Comment by craigham** [comment]
I think it is doing that conversion for you, so I guess it does work, but it is throwing that warning.  Wouldn't it be better to be setting to StringType

i.e.
`updateState(OmnilinkBindingConstants.CHANNEL_ZONE_CURRENT_CONDITION, new DecimalType(current));`

should be 
`updateState(OmnilinkBindingConstants.CHANNEL_ZONE_CURRENT_CONDITION, newStringType(current));`

**Comment by digitaldan** [comment]
>when you say installed the binding, how are you doing that? I

I am running the binding within a OH instance, so I am installing new versions using the karaf console, running from eclipse is probably better :-) 

>The channels.xml for the zone channels defines it as a string,

Hmm, yes I rushed it.  It should probably be a decimal (0,1,2,3)

**Comment by digitaldan** [comment]
I will fix that since I'm in there right now
