### ISSUE TITLE
how to expose jomnilink Connection via bridgehandler

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#15]
Dan,

Wondering what your thoughts are on accessing the omnilink from the individual handlers.

I have this in the bridge handler. (note the 'New' at end of method will disappear) - getting rid of the NIO.

`private ObjectStatus requestObjectStatusNew(final int objType, final int startObject, final int endObject,
            boolean extended) throws OmniInvalidResponseException, OmniUnknownMessageTypeException {
        try {
            return omniConnection.reqObjectStatus(objType, startObject, endObject, extended);
        } catch (OmniNotConnectedException | IOException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.BRIDGE_OFFLINE, e.getMessage());
            // do we need to reconnect, or will reconnect listener get called?
        }
        return null;
    }`

Do you think any caller of this uses the ObjectStatus return?  Or could we utilize generics to return UnitStatus, etc.  Also, if we also threw an objectnotfound exception, we could never return null I believe.  

Note, this is in the bridge, so when any of the handlers call it when we have connection issues, etc, the bridge will be able to detect and go offline.

Thoughts?

**Comment by craigham** [comment]
Currently there is a method on the bridgeHandler

`public void sendOmnilinkCommand(final int message, final int param1, final int param2) {

        listeningExecutor.execute(new Runnable() {

            @Override
            public void run() {
                try {
                    omniConnection.controllerCommand(message, param1, param2);
                } catch (IOException | OmniNotConnectedException | OmniInvalidResponseException
                        | OmniUnknownMessageTypeException e) {
                    logger.debug("Error in sendOmnilinkCommand", e);
                    // TODO should we be changing status of bridge on any of these errors?
                }
            }
        });
    }`

refactoring from nio would look something like:

`public void sendOmnilinkCommandNew(final int message, final int param1, final int param2)
            throws OmniInvalidResponseException, OmniUnknownMessageTypeException {

        try {
            omniConnection.controllerCommand(message, param1, param2);
        } catch (IOException | OmniNotConnectedException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR, e.getMessage());
            logger.debug("Error in sendOmnilinkCommand", e);
        }

    }`

Then the 'quirky' code can go in those handlers.

However, do need to think about if method like this should throw IOException, or do we create other way of notifying the handlers there was a problem.  Could just catch, update status, and re-throw too.

**Comment by craigham** [comment]
I think this sendOmnilinkCommand was like what you were suggesting, right?

**Comment by digitaldan** [comment]
> think this sendOmnilinkCommand was like what you were suggesting, right?

Yep! So it should throw either an OmniInvalidResponseException | OmniUnknownMessageTypeException to the handler since both are recoverable.  Also i am just thinking it should maybe also throw a BridgeOfflineException (new class) if the bridge catches a IOException or OmniNotConnectedException (or is just not connected) , that way the handler does not need to do anything for those.

**Comment by craigham** [comment]
sounds good to me.  I am refactoring upb units to be non-blocking, so maybe we can work through that handler to nail things down?  I should be able to check in something in the next 10 mins, just testing.

Dan, another question.  Though you would never know it by looking at the binding, I am a big fan of unit testing.  I was wondering if you know of a good way to get junit testing into a binding.  I have seen some bindings with test bindings etc, but when I was starting on creating bindings I found the documentation a little scare (understandably).  Any suggestions on that front?

**Comment by craigham** [comment]
Dan,

Could you take a look at 

https://github.com/QuailAutomation/openhab2-addons/commit/085e847dd4059af712efedcde68e48e6aa0667c3

My upb units now do not call the NIO stuff.

Let me know your thoughts.

**Comment by craigham** [comment]
fyi, the reason I started with units is because I know you don't have any so less chance of a merge conflict....

**Comment by digitaldan** [comment]
>Dan, another question. Though you would never know it by looking at the binding, I am a big fan of unit testing. I was wondering if you know of a good way to get junit testing into a binding. I have seen some bindings with test bindings etc, but when I was starting on creating bindings I found the documentation a little scare (understandably). Any suggestions on that front?

I'm a fan too, but have not done much in OH with testing.  I would look at https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.hue.test for an example.  Also I know that we are discouraging groovy tests, so I would stay away from those.
