### ISSUE TITLE
Why is this not in the core project

### ISSUE THREAD

**Issue by ecdye** [QuailAutomation/openhab2-addons#150]
Is there any particular reason that the omnilink add-on has not been incorporated into the core openhab-addons repo?

**Comment by craigham** [comment]
There is a lot of work required to get the binding accepted into the main repo in terms of documentation, etc.

I can only speak for myself, but I do not have time to complete those tasks.

**Comment by ecdye** [comment]
Would you be okay with me updating and making it acceptable the main repo and submitting it for admission?

**Comment by craigham** [comment]
absolutely.  it would be great to have the binding more accessible.

**Comment by cole701** [comment]
I still have a working OmniPro II Test Rig is anything needs to be vetted
and tested...  It has been a while since I have been in the project...
