### ISSUE TITLE
Align Omnilink motion item type with other OH devices

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#152]
Currently the Omnilink binding uses a Contact item type for motions which output an "OPEN" or "CLOSED" state.  
Other common OH devices (like zwave) use a Switch item type with an "ON" or "OFF" output for motion detectors.

The difference in item types forces the need to convert one or the other for usage in occupancy rule logic.

**Comment by boc-tothefuture** [comment]
Hi @swamiller Not sure what we should do for this one.. because a motion sensor really is a contact and certainly that is how Omnilink views it in the protocol.

**Comment by swamiller** [comment]
No worries, looks like zwave might be the odd setup.  I'll close the issue.
