### ISSUE TITLE
periodic refresh

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#23]
Dan,

There is a periodic refresh in the bridge handler (see scheduleRefresh()).

Right now every 6 hours (this could be made configurable) the system queries the omnilink for the statuses (units only at this time) just to make sure openhab has not missed something, for whatever reason.  

Do you think this is bad idea?

**Comment by boc-tothefuture** [comment]
While I am not @digitaldan.. I did see that in the driver and was wondering if we needed it... I haven't seen the driver miss anything when I was playing with it.  
My general thoughts/vote if I have one, is to remove it until we have evidence that it is necessary?
Less code (unless we have a demonstrated need for it) is usually better in my opinion.

**Comment by craigham** [comment]
Thanks for the input Brian.  I shouldn't have directed the question
directly to Dan.  My bad.

I kind of like the periodic refresh if only once a day.  I have also used
an isy which is a dedicated insteon device, and I know it internally
queries each device once a day at 3am just to make sure state changes
haven't been missed.

**Comment by digitaldan** [comment]
I actually almost opened an issue around it now that you mention it.  As long we have have a connection there is no need to do a refresh, as @boc-tothefuture mentioned , i have never seen loosing events.  The only object we need to poll for is audio-source status messages, but that should probably be done in the handler.  I would also vote to remove it.

**Comment by craigham** [comment]
Ok, no problem let's remove it.

**Comment by craigham** [comment]
Guys, I'll remove this when I get back from vacation, which is the 30th.

**Comment by digitaldan** [comment]
You're in Spain, no rush ;-)

**Comment by craigham** [comment]
removed
