### ISSUE TITLE
Label override?

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#24]
Dan, in the area.xml file for the channel definition the same channel type is used for each.  It would make for a friendlier user experience if we overrode the channel label/description.  Did you not do that because you don't like that, or just haven't gotten to it yet?

			<channel id="disarm" typeId="area_command" />
			<channel id="day" typeId="area_command" />
			<channel id="night" typeId="area_command" />
			<channel id="away" typeId="area_command" />
			<channel id="vacation" typeId="area_command" />
			<channel id="day_instant" typeId="area_command" />
			<channel id="night_delayed" typeId="area_command" />

Those all show as Security Command right now in PaperUI, control section.  Could have Away, Night, etc.

**Comment by craigham** [comment]
And in case you don't know what i mean, here is an example of using same channel def, but overriding the label/desc

			<channel id="scenea" typeId="scene_toggle">
				<label>Scene A</label>
			</channel>
			<channel id="sceneb" typeId="scene_toggle">
				<label>Scene B</label>
			</channel>
			<channel id="scenec" typeId="scene_toggle">
                              <label>Scene C</label>
                        </channel>
                        <channel id="scened" typeId="scene_toggle">
                             <label>Scene D</label>
                       </channel>

**Comment by digitaldan** [comment]
> Did you not do that because you don't like that, or just haven't gotten to it yet?

Just have not done it yet, its a good idea.

**Comment by craigham** [comment]
I'm just about to hop on a plane.  Otherwise i would take care of it.

**Comment by digitaldan** [comment]
Safe travels, I'm on holiday tomorrow, so my contributions will be sparse over the next week.

**Comment by craigham** [comment]
I'm heading over to Europe so my contributions might be sparse for almost
two weeks as well.
