### ISSUE TITLE
Auto-discovery not adding things to a specific bridge

### ISSUE THREAD

**Issue by digitaldan** [QuailAutomation/openhab2-addons#26]
Last night I noticed that my omni things did not actually reference my bridge, for example:

`{channel="omnilink:zone:1:contact"}`

This makes no reference to this zone thing being part of a bridge, assuming I called my bridge 'home' (and not the random name it defaults to), it should look like:

`{channel="omnilink:zone:home:1:contact"}`

I'm surprised that this has actually been working!  I guess ESH defaults to the first instance it finds of a thing handler if a bridge is not specified.

In any case, I have a fix I will check in shortly.

**Comment by craigham** [comment]
I'm a little confused.  Doesn't the following, found in the Discovery  code, notice the withBridge call do the linking?

`                discoveryResult = DiscoveryResultBuilder.create(thingUID).withProperties(properties)
                        .withBridge(this.bridgeHandler.getThing().getUID()).withLabel(o.getName()).build();
                thingDiscovered(discoveryResult);
`
And from Karaf I see this, where it does appear the bridge is linked (look for Bridge=)

`openhab> smarthome:things list
omnilink:upb:5 (Type=Thing, Status=ONLINE, Label=Foyer: EntryHallway, Bridge=omnilink:controller:omni)
omnilink:area:1 (Type=Thing, Status=ONLINE, Label=Main Area, Bridge=omnilink:controller:omni)
omnilink:controller:omni (Type=Bridge, Status=ONLINE, Label=Omnilink controller, Bridge=null)
omnilink:upb:30 (Type=Thing, Status=ONLINE, Label=Dining Room: Vase LightsN, Bridge=omnilink:controller:omni)`


What am I missing?

**Comment by digitaldan** [comment]
Without specifying the bridge when creating a thing, my things, at least in the PaperUI did not contain the bridge id.  Also I just checked the Hue binding, it also creates the thing with 

`ThingUID(thingTypeUID, bridgeUID, light.getId());` 

and then returns the result  with 

`DiscoveryResult discoveryResult = DiscoveryResultBuilder.create(thingUID).withThingType(thingTypeUID)
                    .withProperties(properties).withBridge(bridgeUID).withLabel(light.getName()).build();`

I have not looked under the hood why you need both.

**Comment by boc-tothefuture** [comment]
@digitaldan is this still valid?  Or has this been merged in?
