### ISSUE TITLE
item IDs parsing can cause errors on manual thing configuration

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#28]
This defect came up while I was testing the thermostat setup.  I copied the following code that is in a lot of our handlers in the channelLinked method:
`logger.debug("channel linked: {}", channelUID);
 String[] channelParts = channelUID.getAsString().split(UID.SEPARATOR);
 int zoneId = Integer.parseInt(channelParts[2]);`
We use that to get the zone/thermostat/etc ID.  However, this is only working because (from what I can tell) the convention that the paper UI uses to create channelUIDs.  If you configure this manually (which some people may do, and I needed to during testing) you will get an error if that second part isn't a number.  For example, I named thermostat downstairs instead of 1.

This code works across both the manual and paperUI method and as an added bonus doesn't rely on positional parsing in a string:
`int thermostatID = ((Number) getThing().getConfiguration().get("number")).intValue();`

I am proposing we change the other handlers to match.

**Comment by craigham** [comment]
Thanks a great catch Brian.

**Comment by digitaldan** [comment]
👍

**Comment by boc-tothefuture** [comment]
Closed by #36
