### ISSUE TITLE
Use iterable to for object property requests/responses

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#32]
If we agree that the the method I used in the [thermostat driver](https://github.com/QuailAutomation/openhab2-addons/pull/29/files#diff-4c95fe391ef5277755765fcccbcbfb19R161) is a good way to access object property responses I will go ahead and update the rest of the items to use the same method.

@digitaldan and @craigham

**Comment by digitaldan** [comment]
👍

**Comment by craigham** [comment]
Ditto for me

**Comment by boc-tothefuture** [comment]
This was merged, so I am closing this issue.
