### ISSUE TITLE
Remove string parsing for handler commands

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#39]
While I was implementing the audio, I was looking at the russound driver.  It appears you can do the command/channel detection without having to manually parse the channelUID as a string.  For example to get the command we do this in many of our handlers:
```   
String[] channelParts = channelUID.getAsString().split(UID.SEPARATOR);
logger.debug("Channel Parts {}", (Object[]) channelParts);
String channelID = channelParts[3];
```
The channelID is then used as the command that switch on to determine what action to take.  When I looked at the russound driver, they use `channelUID.getId();` which appears to do the same thing.  I am proposing we remove our channel string parsing and use the built in method for all our handlers.

I will make the update to our handlers @craigham  and @digitaldan agree.

**Comment by craigham** [comment]
Another nice catch @boc-tothefuture .  I've been contributing to that binding as well, though that use of the API was not mine, I should have picked up on it...just a little embarrassing....

**Comment by boc-tothefuture** [comment]
Shouldn't be embarrassing, that is the benefit of multiple people working on a code base.  :-)

**Comment by boc-tothefuture** [comment]
This was merged, so I am closing this issue.
