### ISSUE TITLE
zones not calling channelLinked

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#46]
@digitaldan (I think you wrote the zone code? if not maybe its @craigham )- 
  I am not sure if this is an actual *issue* or I just need a second set of eyes here.  I am NEVER seeing channelLinked called for zones.  I set the breakpoint, add a zone using things and items config.  It looks like this:
```
Bridge omnilink:controller:home [ ipAddress=“baz”, port=4369, key1=“foo”, key2=“bar” ] {
   omnilink:thermostat:downstairs "Downstairs Thermostat" @ "Foyer" [ number=1 ]
   //Doors
   omnilink:zone:23 "Garage Door 1" @ "Garage" [number=23]
}
```
In items I have this
```
//Doors
Contact Zones_Garage_Door1_Status  "Status: [%s]" { channel="omnilink:zone:23:zone_contact" }
```
Do either of you see the same behavior?  I don't see this behavior in thermostats or audio zones (only things I have migrated so far).  The net result is that when openhab is restarted I have no status for my zones.

When the state of the door changes, the event is fired and the handler does get called to update the status.

**Comment by craigham** [comment]
@boc-tothefuture i won't be able to check before Sat.

**Comment by boc-tothefuture** [comment]
No problem.  Maybe @digitaldan can validate my sanity.  :-)

**Comment by digitaldan** [comment]
I'll take a look, my zones all load fine, but I don't manage my Things in files, only items and sitemaps, so that might be a clue why its working different.

**Comment by boc-tothefuture** [comment]
Took another look at this.  channelLinked is called when the item is added from the paper UI but not from a things file.  I will try and understand what could/would be different about that behavior.

**Comment by boc-tothefuture** [comment]
So this works:
```
omnilink:zone:home:23 "Garage Door 1" @ "Garage" [number=23]
```
But adding that third element is not required for thermostats or rooms.  Still looking at why it is for zones.

**Comment by boc-tothefuture** [comment]
I am going to rescind my previous comment, even with the third element in its not calling channelLinked - there was some leftover cruft from when I was messing with paperUI that was confusing me.

**Comment by digitaldan** [comment]
When adding things within a bridge, should it not look like:
```
Bridge omnilink:controller:home [ ipAddress=“baz”, port=4369, key1=“foo”, key2=“bar” ] {
  thermostat downstairs "Downstairs Thermostat" @ "Foyer" [ number=1 ]
   //Doors
  zone 23 "Garage Door 1" @ "Garage" [number=23]
}
```

**Comment by boc-tothefuture** [comment]
@digitaldan - 
  I gave that a try, the issue still persists.

**Comment by digitaldan** [comment]
So strange, I'm sure there's a typo somewhere, I'll take a look at it on Thursday or Friday when I have a free moment.

**Comment by boc-tothefuture** [comment]
Ok, I also opened a thread on the community forum to ask.

**Comment by boc-tothefuture** [comment]
Ok.  So there were a couple of issues that I tracked down by stepping through the linking of objects.
The error was in the items file, I was referencing the type_id not the channel id.  I had to change it from zone_contact to contact.
This works as expected:
` Contact Zones_Garage_Door1_Status  "Status: [%s]" { channel="omnilink:zone:home:garage1:contact" } `

Closing this issue.
