### ISSUE TITLE
omni: area handler issue with manually created area...classcastexception

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#56]
When I manually create an area using paperui, the following line in handleCommand throws a classcastexception.

int areaNumber = (int) getThing().getConfiguration().get(OmnilinkBindingConstants.THING_PROPERTIES_NUMBER);

Discovery is not working for me right now, but I have a feeling when using PaperUI, a big decimal is used for the area number.  I assume discovery is setting it to int/Integer.  Maybe we standardize discovery to use whatever paper would use to keep code simpler in area handler, or we could handle either.

**Comment by boc-tothefuture** [comment]
@craigham - 
  This is fixed in my implementation_fixes branch.  I moved it to using the same method we use for all the handlers.

**Comment by boc-tothefuture** [comment]
I was waiting to push my implementation fixes branch up when I was done dogfooding the new driver, but maybe since you are hitting some of the same snags I did, I should PR it now?

**Comment by craigham** [comment]
ya I think we might as well PR it.

**Comment by craigham** [comment]
this is fixed.
