### ISSUE TITLE
Thermostat support is missing from the V2 driver

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#6]

**Comment by boc-tothefuture** [comment]
I will begin working on this issue.

**Comment by boc-tothefuture** [comment]
@craigham and @digitaldan - 
  I have a silly question.  I am starting to work on the thermostat support here.  Previously, my edits were small so I was just using a combination of vi and atom.  For this one, I want to make sure I am sticking to the eclipse smarthome guidelines.  

How do you get the new omnilink driver to show up in the smarthome eclipse IDE?  I change the branch to be one of the newer ones (like the things branch @digitaldan setup) and I have the files on disk.  However, it doesn't show up as a new project in the package explorer.
If I try to import it as a new maven project, eclipse refuses because of a naming conflict (not sure with what).

Is there some magic to making the project show up in eclipse?

**Comment by craigham** [comment]
Try closing your the 1.x versions n of the project using java explorer
workspace.  Or add -1 to prior version.

**Comment by boc-tothefuture** [comment]
Thanks @craigham..
What I ended up doing was just wiping my current install and doing a fresh install.  This time without any of the V1 addons. 

I can now import the project and it shows up.  I do however, get a pom error for maven. 
`Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (execution: default, phase: compile)	pom.xml	/org.openhab.binding.omnilink	line 6	Maven Project Build Lifecycle Mapping Problem`
It appears to not like this in the maven pom:
`  <parent>
    <groupId>org.openhab.binding</groupId>
    <artifactId>pom</artifactId>
    <version>2.1.0-SNAPSHOT</version>
  </parent>`

Did you run into this?  I will keep digging..  I am mostly bringing it up in case it is something we have to resolve before we do a PR into the main openhab addons branch in the future.

**Comment by boc-tothefuture** [comment]
@craigham and @digitldan - 
  Are you exercising/testing the driver directly from eclipse or are you copying it into a running system every time you want to test?  
  If you are testing it from eclipse how are you doing that?

**Comment by craigham** [comment]
I  run it in debug mode (look under run configurations, or check on
internet for directions).

I find if i leave automatically compile/build from the project options it
does a good job of hot swapping in the newly compiled classes.  Doesn't
work if you change xml, or static stuff.

**Comment by boc-tothefuture** [comment]
@craigham - Are you kicking off the paperUI in debug mode or just the omnilink driver directly?

**Comment by craigham** [comment]
I run openHAB in debug mode.  I really never run the omnilink driver
directly.

**Comment by boc-tothefuture** [comment]
@craigham and @digitaldan
In the [discovery service](https://github.com/QuailAutomation/openhab2-addons/blob/digitaldan-omnilink-binding-thing-types/addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java) is there any concern if I rename some of the private methods.  They are all named generateXXX (I think this is carried over from the v1 binding?).  Its in the discovery service so I was going to propose renaming them all to discoverXXX which I think better communicates the intent of the methods.

**Comment by boc-tothefuture** [comment]
@digitaldan - You had made a comment about removing the C and F for temperature stuff in the binding because the user sets the mode already.  I see it still in the thermostat.xml thing.  Is it safe for me to remove that now?

**Comment by boc-tothefuture** [comment]
@craigham I am trying to make sense of some of the discovery code.  For things like [generateButtons()](https://github.com/QuailAutomation/openhab2-addons/blob/digitaldan-omnilink-binding-thing-types/addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java#L76) why is it looping through the areas?  I also see it adding the area as a property of a button.  But I didn't think buttons were in any way associated with areas?

Thanks

**Comment by craigham** [comment]
@boc-tothefuture , you'll have to ask @digitaldan about generateButtons.  Dan refactored it.

Refactoring the name to discover seems like a good idea to me.

**Comment by boc-tothefuture** [comment]
@craigham and @digitaldan 
   I am building the thermostat stuff to only work on omnilink versions 3.x and above..  I assume that covers most of our user base. 
  Let me know if you think we need to support 2.x

**Comment by digitaldan** [comment]
>I am building the thermostat stuff to only work on omnilink versions 3.x and above.

👍

**Comment by boc-tothefuture** [comment]
@digitaldan and @craigham 
Is there something wrong w/ this channel definition?
`<channel-type id="thermostat_status">
		<item-type>Number</item-type>
		<label>Thermostat Status</label>
		<description>Current Thermostat activity</description>
		<category>Temperature</category>
		<state pattern="%d" readOnly="true">
		<options>
                <option value="0">Off</option>
                <option value="1">Heating</option>
                <option value="2">Cooling</option>
                <option value="3">Humidifying</option>
                <option value="4">Dehumidifying</option>
        </options>
        </state>
	</channel-type>`

This will just show the number value in the paper UI.  If I remove the readOnly it will map the value appropriately in the paper UI.   I am mostly wondering if I should be doing something differently for readOnly values that have options or if this is just a limitation of the paper UI?

**Comment by boc-tothefuture** [comment]
@digitaldan - I am done with the thermostat implementation.  I went to merge in the latest changes from here and it appears that some Console elements were added to jomnilink but were not pushed to master for that repo?  So when I built the latest thermostat stuff off of master it didn't pull in the console elements, which is now causing my build to fail for the binding.  Can you push those up to master for jomnilink when you get a chance?

**Comment by boc-tothefuture** [comment]
@craigham  - 
  Question, I am supposed to me merging/PR against the digitaldan branch now, right?  Or is it still against omnilink-binding branch?

**Comment by craigham** [comment]
Against digital dan branch still.

**Comment by boc-tothefuture** [comment]
closed by #31
