### ISSUE TITLE
Inconsistent channel names (Units vs. Rest)

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#60]
In our other thing definitions we use snake case to separate words.  For example:

```
<channel id="activate_keypad_emergency" typeId="omni_activate_keypad_emergency" />
```

However, in units we switch to smush case 
```
<channel id="scenea" typeId="scene_toggle">
                <label>Scene A</label>
            </channel>
```
I think that should become 'scene_a'

I am happy to make the change if we agree.

**Comment by craigham** [comment]
sounds good to me.
