### ISSUE TITLE
omni: consoles not discovered

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#62]
the generateConsoles has been commented out, with a comment saying it throws an error.

I enabled the call again to try it, and indeed it does throw an error.

**Comment by digitaldan** [comment]
So, the docs implies this should work, but of course it does not.  This weekend I fired up the HAI PC Access program, interesting enough, unlike the other "objects",  it shows four default consoles to configure ( I only have one).  This is the max number for the LTe board.  So I think either users will have to add these manually or we sudo auto discover the max number of consoles for the type of system (as PC access kinda does)

**Comment by swamiller** [comment]
For the record, the Console Beep functionality that now shows up in the Paper UI does turn the beep on and off but doesn't effect the number of beeps as the drop down implies.  0 is off, any other number is on (single beep).

**Comment by boc-tothefuture** [comment]
Following up on what @digitaldan said.  I took a look at the protocol docs... And the docs indicate you can request console object properties, but the docs I have do not define a response describing the console properties. I am guessing its not actually implemented?

Do we want to remove the commented out code and close this issue?

**Comment by digitaldan** [comment]
> I have do not define a response describing the console properties. I am guessing its not actually implemented?

Thats my guess as well, so for consoles, do we make this a manual configuration only?  Or do we add the max number of consoles the system supports (kinda what PC access does) during discovery?  I'm ok with with manual adding.

**Comment by craigham** [comment]
I agree with manual.

**Comment by boc-tothefuture** [comment]
Manual is good.  I have removed the generateConsoles from my implementation_fixes branch.  So, we can close this once I PR that.

**Comment by digitaldan** [comment]
Sounds good, I actually have a PR open to remove them, but I can close it if thats easier.

**Comment by boc-tothefuture** [comment]
Nope, leave it.  I can just merge yours in once it goes into this branch.  Then we can clear this item quicker.

**Comment by boc-tothefuture** [comment]
@craigham I think this can be closed now with #67 merged.
