### ISSUE TITLE
Omnilink Lock Support

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#63]
Add the ability to control door locks (Access Control in HAI/PC Access terms).

**Comment by boc-tothefuture** [comment]
Looked at the API.  This looks like it is possible.

**Comment by swamiller** [comment]
Yes, please.  I would still prefer controlling/status my locks through my alarm panel (as master) versus OH.  I have some creative flag use now to make it work in OH.

**Comment by boc-tothefuture** [comment]
@swamiller - 
  I have added lock support, but I have no way to verify it works.  Can you install this test version and provide feedsback?

https://github.com/boc-tothefuture/openhab2-addons/releases/download/locks/org.openhab.binding.omnilink-2.4.0-SNAPSHOT.jar

**Comment by swamiller** [comment]
@boc-tothefuture 
So far, so good! I installed the test version and created new door lock items.  They seem to function ok for the first install.  I'll do more testing and update.

**Comment by swamiller** [comment]
I removed all my work around flags from my Omni, created OH items for each lock, and all seems to function as desired.

One question, there is a logEvent for "LogEvent changed from DOOR LOCKED to DOOR UNLOCKED" which is helpful.  Is there a way to append the item name to know which door?  Not a deal breaker, more of a question.

Thank you!!

**Comment by boc-tothefuture** [comment]
@swamiller - If I am understanding you correctly, you are talking about the logEvent text which comes from polling the omni.  The Omni is the one responsible for that text, the binding doesn't modify it.

**Comment by swamiller** [comment]
LGTM, thank you @boc-tothefuture!
