### ISSUE TITLE
Status no longer updates with custom UID names.

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#70]
After merging #69 status is no longer updated on my system.

#69 makes an assumption about the UID (namely that its an automatically assigned number from paperUI).  This breaks a system where the UID is assigned manually and doesn't match (such as when defining things yourself).

I will take a look at this later tonight to see if there is a way to remove the caching (and the complexities it brings) yet not break status update for manually assigned UIDs.

**Comment by craigham** [comment]
I have seen this as well.  It appears to me that we will have to force a Id format if we want to look up child things as we have now.  

I was looking at how other bindings handle this haven't found anything definitive yet.

**Comment by boc-tothefuture** [comment]
I think we *should* be able to do it without forcing a format.  We can iterate over the things registered to the bridge and match them based on the number of the thing itself (it should be a property of the thing)..  
I haven't had a chance to implement it, and probably wont until tonight.. But it should work if I understand this correctly.
It will be O(n) which is a bit appalling - but.. amazing, getThingbyUID is also O(n).. I am surprised its not a map.

**Comment by craigham** [comment]
didn't dig in to see getThingbyUID is O(n), that is surprsing.  I suppose iterating all the time won't be an issue for most users for this binding...

**Comment by boc-tothefuture** [comment]
Yeah.. I am kind of shocked..  but here is the code:
```
  public Thing getThingByUID(ThingUID uid) {

        Bridge bridge = getThing();

        List<Thing> things = bridge.getThings();

        for (Thing thing : things) {
            if (thing.getUID().equals(uid)) {
                return thing;
            }
        }

        return null;
    }
```

**Comment by craigham** [comment]
and I do like not forcing a format as well.  If the user is going to create things themselves it is nice to have meaningful uids for rules, etc.

**Comment by digitaldan** [comment]
Can you give me an example of a custom thing name?

**Comment by boc-tothefuture** [comment]
Sure.  Here is my thermostat definition in my things file:

```
 //Thermostats
   Thing thermostat downstairs "Downstairs Thermostat" @ "Foyer" [ number=1 ]
   Thing thermostat upstairs "Upstairs Thermostat" @ "Upstairs Hallway" [ number=2 ]
```

**Comment by craigham** [comment]
@boc-tothefuture 

I think your file is actually a little offside with respect to the specified syntax as described here:
http://docs.openhab.org/configuration/things.html

It should follow this:
`Thing <binding_id>:<type_id>:<thing_id> "Label" @ "Location" [ <parameters> ]`

However, I see no reason why you couldn't have 
 Thing omnilink:thermostat:downstairs "Downstairs Thermostat" @ "Foyer" [ number=1 ]

And this would break that prior lookup as far as I can tell.  We were forcing
 Thing omnilink:thermostat:<thermo #> "Downstairs Thermostat" @ "Foyer" [ number=1 ]

**Comment by digitaldan** [comment]
i see, so your thing ID  is not the number but a specified name. @boc-tothefuture I'm assuming this is inside a bridge definition  block?

**Comment by boc-tothefuture** [comment]
@craigham Yeah, it is confusing because once you are inside a bridge block the format can change.  See this thread here:  https://community.openhab.org/t/current-and-correct-documentation-of-syntax-for-things-and-items-needed/24864

@digitaldan - Yeah, because I wasn't auto generated with paperUI I just named my things names that represented  them.  

I should probably get over it and move to paperUI, but I find it really nice to have my configuration files as text and stored in git. 

As I was migrated form the 1.x binding to this binding it was very useful to have all my configs in git and just change branches between the 1.x configs and the 2.x configs.

**Comment by craigham** [comment]
I don't think it is even about using PaperUI.  If a user manually creates a zone or console, etc, it is pre-populated with a seemingly random meaningless string.  It was just our discovery that is using the # for the thing id.

**Comment by digitaldan** [comment]
Yep, we need to support custom names, i just knew that was to easy of a fix :-)  @boc-tothefuture I'll take a look at #71
