### ISSUE TITLE
Alarm State Rules Triggered on entryDelay

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#80]
We receive a state update from the omni when a perimeter zone  is opened.  The state is the same state we were in before (away/vacation, etc) but it now has an entryTimer field set to a non-zero value.

This causes an issue w/ rules that are based on the omni state.   For example:
```
rule "Lock all Doors"
when 
	Item Alarm_Mode received update
then
  logInfo("Omnilink", "Checking door lock instructions for state {}.", Alarm_Mode.state)
  if (Alarm_Mode.state == 1 || Alarm_Mode.state == 2 || Alarm_Mode.state == 3 || Alarm_Mode.state == 4 || Alarm_Mode.state == 5 || Alarm_Mode.state == 6) {
      //Don't relock on enter.
      logInfo("Omnilink", "Alarm Mode {}", Alarm_Mode);
      logInfo("Omnilink", "Security Mode State changed to {}.  Locking doors.", Alarm_Mode.state)
      sendCommand(SceneLockDoors, ON)
  }
  else{
  	 logInfo("Omnilink", "Security Mode State changed to {}.  Not locking doors.", Alarm_Mode.state)
  }
end
```
We don't expose the exitDelay or entryDelay so uses can't write rules around them..  In my opinion the alarm state as we measure it (Away/Night/etc) hasn't changed.  I am thinking we just drop those updates on the floor?  
If we see a use for it, we can create an exitDelay and enterDelay channel if people want to track those?

Thoughts @craigham and @digitaldan ?

**Comment by digitaldan** [comment]
>We receive a state update from the omni when a perimeter zone is opened. 

Hmm, I did not know that

So this can be handled a few ways.  The first is in your rule, you are triggering on 
```
Item Alarm_Mode received update
```

If you instead used
```
Item Alarm_Mode changed
```

You can also get the previous value in rules if you wanted to compare current with last value. 

We could also drop updates on the floor, in this case we would need to keep a local version up the zone status object to compare against.   

I think it could be useful to expose the delay, I could see rules written around that as well.  We may want to create channels for them.

**Comment by boc-tothefuture** [comment]
I didn't think about changed instead of update..  that is maybe a better solution for this particular problem?

Although, not sure we should send an update when the value doesn't change? What is normal in OpenHAB?

I am not sure there is a need to store the last value.  I had to implement this before I got your response.  It seems to work as I would expect with just dropping any status that has an entryTimer on it.  I will try to back out my change and see if on changed works.

**Comment by digitaldan** [comment]
>Although, not sure we should send an update when the value doesn't change? What is normal in OpenHAB?

Well the harm in sending updates frequently is you end up generating unwanted noise, for the system and clients connected to rest endpoints. So you want to avoid frequent updates if nothing has changed.  Infrequent updates when nothing has changed is normal behavior. Think about code that eventually invalidates its cache after x amount of time, so rules do need to be specific to updates vs changes if it matters.

**Comment by boc-tothefuture** [comment]
I think we can close this one.  I moved my code to updated as suggested by @digitaldan .
