### ISSUE TITLE
User codes should be of type string.

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#82]
Summary from code comments: 

@digitaldan -
I meant to open an issue on this for discussion, but I forgot. It started out that the item type was of type Decimal, which was causing the code to fail. I accepted the thing type as canonical, so, I changed the code to match the thing type. However, once I got later into the code it became clear that because leading zeros are valid in a code, its really a string type and we had to discuss which was correct the item type or the code. So, I added the conversion bit you see to make things and I meant to open an issue for discussion, but I forgot.
I think string type is correct. I will be happy to revert all the code back to string type - but it wont happen for several days. I will open an issue now so we don't lose it and we can move discussion over there.

Further discussion is [here](https://github.com/QuailAutomation/openhab2-addons/commit/2a3579abc9a0f4f8ae8881b3766d837f9cc6092a#commitcomment-23190437)

**Comment by digitaldan** [comment]
Well, since we are both in complete agreement, this is a easy one to fix :-)   I will submit a PR to fix shortly.

**Comment by craigham** [comment]
just merged PR, closing
