### ISSUE TITLE
Alarm Channels

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#85]
Setting up my .items file, I noticed alarm modes have been separated into individual channels.  Since you can only select one alarm mode setting at a time, what was the thought behind making each setting its own channel?  Seems more intuitive for there to be one alarm channel with modes to be selected.

**Comment by craigham** [comment]
there is no mechanism for passing in both a 'mode' and security code to a channel, i.e. can't have more than one parameter (command) sent for a channel.

therefore each of those channels is for setting a particular mode.  the user/openhab has to pass in the security code desired to try change the security mode.  Imo it does match the interface you see on the wall units, both keypad and touchscreen....you first pick which mode you want to switch it to, then it asks for security code.

**Comment by swamiller** [comment]
Does selecting a different mode "unselect" the current mode?

**Comment by craigham** [comment]
the mode channel is the only channel which reflects the current mode.  each of those other channels are 'action' channels so to speak.  after they have been sent the command with the user code, they reset back to None for state.  they really don't hold state.
