### ISSUE TITLE
omnilink - area channel definitions 

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#86]
@digitaldan @boc-tothefuture I was just looking at the areas thing def, and was wondering if it would make sense to define the alarm channels more as the arming channels are.  i.e. just override the label/description and use 1 channel instead of a channel for each type of alarm.

After defining both ways do you have a preference?

**Comment by digitaldan** [comment]
The system can be in more then one alarm, so for instance both fire and burglary, so I think they need to be separate channels.

**Comment by boc-tothefuture** [comment]
>The system can be in more then one alarm, so for instance both fire and burglary

Well, that is a pretty bad day.

**Comment by craigham** [comment]
That is a pretty sad day.  Recently we've had a bunch of wildfire evacuations up here in BC, and why of course there has been looting.  

I didn't mean consolidate the channels....I meant consolidate the channel definitions.  

`<channel id="day" typeId="area_command">
				<label>Arm Day Command</label>
				<description>Send a 4 digit user code to arm the system to day</description>
			</channel>
			<channel id="night" typeId="area_command">
				<label>Arm Night Command</label>
				<description>Send a 4 digit user code to arm the system to night</description>
			</channel>`

These all use 1 channel definition area_command.

If we like this style better, all the alarms could be consolidated as well to 1 definition.

**Comment by digitaldan** [comment]
Ah, yes that does make sense.  I think that sounds like a good plan.

**Comment by boc-tothefuture** [comment]
@digitaldan and @craigham Where did we land on this?  Did we implement or abandon this idea?

**Comment by craigham** [comment]
Probably just didn’t implement.  I will take a look and look into completing the work.

**Comment by craigham** [comment]
@boc-tothefuture this looks like it was done before.  all the channels use "area_command".  

I will close this issue, let me know if I am missing something.
