### ISSUE TITLE
Isy Programs Channel Control Not working In paperui

### ISSUE THREAD

**Issue by robertw** [QuailAutomation/openhab2-addons#89]
Try to work with programs for ISY I was noticing that programs have a Channel called control with type of switch

I selected it in paper and does not seem to function I was hoping (or does it run the then when on and the else when off)?  

Thanks

**Comment by craigham** [comment]
Ok control channel should now be working.

You can now set a string to pass in.  It should be the clause of the program you intend to execute.

eg.

runIf
runThen
runElse

**Comment by robertw** [comment]
Sweet..... thank you....
