### ISSUE TITLE
Auxiliary Temperature Zones

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#98]
Is there a channel set up to get auxiliary zone temps and humidity?  My outside temp is shown as a thermostat but none of my other room temps are available
 
I have temp sensors outside and in some of my rooms.  The outside temp is set up to show in the thermostat settings but I can't figure out the channel set up to get my room temp/humidity. 

I tried:
`Number Zone_MasterTemp      "Master Temp: [%d]"      <temperature>      (Zones)      {channel="omnilink:zone:home:11:current_condition"}`

This only provides a string output.

**Comment by BCS-JonW** [comment]
Ditto.   I'm also trying to get aux temp/humidity sensor readings.

**Comment by boc-tothefuture** [comment]
I have some temp sensors but haven't put them in OpenHab yet.  I will take  crack at this one.

**Comment by boc-tothefuture** [comment]
@swamiller when you say 'String Output' does that mean its just showing the value and not converting it to a temperature?

**Comment by BCS-JonW** [comment]
There is no temperature value output - numeric or string.

**Comment by swamiller** [comment]
Because the omni treats extended temp/humidity sensors like zones, I only get a string zone status (CLOSED, secure, Disarmed, etc.) but no temperature value.

**Comment by boc-tothefuture** [comment]
Ok - I started working on the code tonight.  It will probably take a few days.

**Comment by boc-tothefuture** [comment]
@swamiller can you check the latest build and validate it works for you?  I did w/ a temperature but my humidity sensor is broken so I couldn't test that.

**Comment by BCS-JonW** [comment]
I just downloaded the latest from here:  https://s3-us-west-2.amazonaws.com/craigham-pub/org.openhab.binding.omnilink-2.2.0-SNAPSHOT.jar    Is that the correct location?

Still not getting the temperatures.  The channel config looks like this:  {channel="omnilink:zone:home:14:temperature"}

**Comment by craigham** [comment]
yes, that has the latest build.  I am not sure about specifics regarding
the config though.

**Comment by boc-tothefuture** [comment]
@BCS-JonW - its not a zone anymore (those are limited to security zones)
Here is an example if you are defining your Things manually:
`Thing aux_sensor deck_temp "Deck Temp Sensor" [number=30]`
Here is what the item would look like
```
Number Deck_Temp "Temp [%d]" { channel="omnilink:aux_sensor:home:deck_temp:temperature" }
Number Deck_Low "Low [%d]" { channel="omnilink:aux_sensor:home:deck_temp:low_setpoint" }
Number Deck_High "High [%d]" { channel="omnilink:aux_sensor:home:deck_temp:high_setpoint" }
}
```
Swap out temperature for humidity if that is what you are trying to read on the channel.

**Comment by BCS-JonW** [comment]
Great, thanks @boc-tothefuture !  Temperature & humidity is working now.

**Comment by boc-tothefuture** [comment]
@craigham -
  I think this can be closed now.

**Comment by craigham** [comment]
@boc-tothefuture  nice addition.

**Comment by swamiller** [comment]
Sorry I was late to the game, but all works except the "high setpoint" is missing.  The "low setpoint" is available.

**Comment by boc-tothefuture** [comment]
Hmm.  I will double check high setpoint code.

**Comment by swamiller** [comment]
@boc-tothefuture the humidity number is not correct either.  It is mirroring the current temp value, not the humidity value.  Would you like a separate issue opened?

**Comment by boc-tothefuture** [comment]
Hmm.  You have it on a humidity zone I assume?  The calculation for humidity is the same as the calculation for Fahrenheit.

**Comment by swamiller** [comment]
Here are my items:
`Number	OutsideTemp_Current	        "Current: [%d]"	            (Zones_MasterTemp, Thermostats)	  {channel="omnilink:aux_sensor:13:temperature"}
Number	OutsideHumidity	            "Humidity: [%d]"	        (Zones_MasterTemp, Thermostats)	  {channel="omnilink:aux_sensor:13:humidity"}`

**Comment by BCS-JonW** [comment]
@swamiller The extended range temp/humidity sensor wires up using two zones.  Depending how you wired it, your humidity sensor is likely using either zone 12 or 14.

**Comment by boc-tothefuture** [comment]
Temperature and humidity should not be on the same zone number.  In your case 13.  Check your Omni config, at least on mine with the combo sensors they are wired to different zones.

**Comment by swamiller** [comment]
Ah, you are correct @BCS-JonW.  @boc-tothefuture the temperature "thing" lists 3 channels, the low setpoint and the humidity channel with the incorrect channel ID number.  I did find a separate humidity channel listed with the correct channel 14.

**Comment by boc-tothefuture** [comment]
Yeah, it is probably not the best user interface because for every aux_sensor one channel will be wrong (humidity or temp).  I didn't see a method to determine if the sensor was humidity or temp from the API.  But I will look again.

**Comment by boc-tothefuture** [comment]
@craigham -
Sorry for the flip flop here.  Might want to reopen this issue while I look at this some more.

**Comment by swamiller** [comment]
@boc-tothefuture Looks like the aux temp sensors should 3 channels, temperature, low setpoint, and high setpoint.  The temp with humidity will have the same 3 channels plus a separate humidity channel.

**Comment by boc-tothefuture** [comment]
Temp and humidity I think have to be separate items since the have distinct high/low alarms and run on separate physical zones.

**Comment by swamiller** [comment]
Yes, that is true.  Looking at the humidity sensor, it lists 3 channels: temperature, humidity, and low setpoint (like the temp sensor).

**Comment by BCS-JonW** [comment]
@boc-tothefuture   The HAI API does specify separate zone types when the object type is Auxilliary, so you can determine which it is when requesting zones from the panel.

**Comment by boc-tothefuture** [comment]
New code pushed in #103. 
Humidty and Temp are now distinct OpenHab Things.  Which leads to better user experience (don't have null channels that can be confusing).

Examples

Thing definition:
```
   Thing temp_sensor deck_temp "Deck Temp Sensor" [number=30]
   Thing humidity_sensor deck_humidity "Deck Humidity Sensor" [number=31]
```
Item definition:
```
Number Deck_Temp "Temp [%d]" { channel="omnilink:temp_sensor:home:deck_temp:temperature" }
Number Deck_Low "Low [%d]" { channel="omnilink:temp_sensor:home:deck_temp:low_setpoint" }
Number Deck_High "High [%d]" { channel="omnilink:temp_sensor:home:deck_temp:high_setpoint" }


Number Deck_Humidity "Humidity [%d]" { channel="omnilink:humidity_sensor:home:deck_humidity:humidity" }
Number Deck_Humidity_Low "Humidity Low [%d]" { channel="omnilink:humidity_sensor:home:deck_humidity:low_setpoint" }
Number Deck_Humidity_High "Humidity High [%d]" { channel="omnilink:humidity_sensor:home:deck_humidity:high_setpoint" }
```

**Comment by boc-tothefuture** [comment]
@craigham can you reopen this until @swamiller  and @BCS-JonW sign off on it?

**Comment by BCS-JonW** [comment]
@boc-tothefuture  Not sure I'd agree with separating the temperature and humidity.  You're basically duplicating the item definitions and just leaving it to the user to decide which to use based on whether it is a temp or humidity sensor attached (functionally, they'll work identical and would be interchangeable).  

Why not just use a generic channel description like "aux_sensor_value" instead of temp and humidity. This would make it easier to extend into the other aux sensor types as well.

Sensor Type Description
80 Programmable Energy Saver Module
81 Outdoor Temperature
82 Temperature
83 Temperature Alarm
84 Humidity
85 Extended Range Outdoor Temperature
86 Extended Range Temperature
87 Extended Range Temperature Alarm


My reason for looking at it this way is because the underlying HAI protocol supplies these sensor property values the same way for the 8 different aux sensor types.

AUXILIARY SENSOR PROPERTIES
Data 4 output status
Data 5 current temperature or humidity
Data 6 low setpoint
Data 7 high setpoint
Data 8 sensor type
Data 9-24 sensor name

**Comment by boc-tothefuture** [comment]
@BCS-JonW  - 
  Thanks for the feedback.  The only option is for them to be two different 'things' in OpenHab terminology or have two sets of channels for all three settings (sensor value, high and low) so a single aux sensor type would have 6 channels.  The values that get put on the channels for temp vs. humidity are calculated differently.  Humidity values get calculated using the Fahrenheit conversion method from omni, temp values get calculated based on the C/F setting of the controller itself.

All types except the PESM are supported now (81-83, and 85-87) are all considered temperature sensors by the OpenHab add-on.

**Comment by BCS-JonW** [comment]
@boc-tothefuture  - I had completely forgotten that the decoding of the values may be different between humidity and temp based on the controller C/F setting.  In my own apps, I always decoded as F, so I used the same function to convert the values.  Makes sense now.

I downloaded the latest build and updated my Things definitions, but I'm getting a couple errors on startup:

2017-11-09 13:41:43.721 [WARN ] [home.core.thing.binding.ThingFactory] - Could not create channel 'low_setpoint' for thing type 'omnilink:temp_sensor:home:attic_temp', because channel type 'omnilink:sensor_temp_low_setpoint' could not be found.
2017-11-09 13:41:43.721 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'low_setpoint' for thing 'omnilink:temp_sensor:home:attic_temp', because channel type 'omnilink:sensor_temp_low_setpoint' could not be found.
2017-11-09 13:41:43.721 [WARN ] [home.core.thing.binding.ThingFactory] - Could not create channel 'low_setpoint' for thing type 'omnilink:humidity_sensor:home:attic_humi', because channel type 'omnilink:sensor_humidity_low_setpoint' could not be found.
2017-11-09 13:41:43.721 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'low_setpoint' for thing 'omnilink:humidity_sensor:home:attic_humi', because channel type 'omnilink:sensor_humidity_low_setpoint' could not be found.

**Comment by boc-tothefuture** [comment]
Can you post your things file?

**Comment by BCS-JonW** [comment]
Pretty simple Things file since most of my 130+ devices were auto-discovered and added via Inbox in PaperUI.

Bridge omnilink:controller:home [ ipAddress="192.168.1.43", key1="<removed>", key2="<removed>" ] {
	Thing 	temp_sensor 		attic_temp 		"Attic Temperature Sensor" 		[number=14]
	Thing 	humidity_sensor 	attic_humi 		"Attic Humidity Sensor" 		[number=15]
}

**Comment by boc-tothefuture** [comment]
Sorry... Meant items file.

**Comment by BCS-JonW** [comment]
After getting the errors, I went back and added entries for both low and high setpoints, but errors persist whether those entries are there or not.

I'm guessing you just want the relevant lines of items....

Number 		hai_zone_014 				"Attic Temp [%d °F]" 			(Group_Temperature)				{channel="omnilink:temp_sensor:home:attic_temp:temperature"}
Number 		Attic_Low 					"Low [%d]" 						(Group_Temperature)				{channel="omnilink:temp_sensor:home:attic_temp:low_setpoint" }
Number 		Attic_High 					"High [%d]" 					(Group_Temperature)				{channel="omnilink:temp_sensor:home:attic_temp:high_setpoint" }
Number 		hai_zone_015 				"Attic Humidity [%d RH]" 		(Group_Temperature)				{channel="omnilink:humidity_sensor:home:attic_humi:humidity"}

**Comment by boc-tothefuture** [comment]
@BCS-JonW - 
   Thanks for the info. I have a PR in now to fix it.. Curious does low set point work for you even with the error?  It seemed to work on my end.

**Comment by swamiller** [comment]
I just picked up the latest and temp sensors and high low set points work well.  Humidity and humidity high setpoint are correct, but no low humidity setpoint channel exists.

**Comment by boc-tothefuture** [comment]
I just posted a fix for that about an hour and a half ago.  How new is your build?

**Comment by swamiller** [comment]
<Key>org.openhab.binding.omnilink-2.2.0-SNAPSHOT.jar</Key>
<LastModified>2017-11-10T01:56:37.000Z</LastModified>

This build was posted about an hour ago.

**Comment by boc-tothefuture** [comment]
Ok, I will take a look..  it worked for me, but I manually define everything in my tests.

**Comment by swamiller** [comment]
I use the paper UI to find the new things but I have an items file set up with all the omni items.  The 2 temp sensors and the humidity sensor were found properly.  The 3 channels for the temp sensors were found (and linked to my items file properly) but the humidity channel only found 2 channels, humidity and high setpoint.

**Comment by boc-tothefuture** [comment]
@swamiller -> Just put a PR in.  Was a typo in the channel definition.

**Comment by swamiller** [comment]
![image](https://user-images.githubusercontent.com/17254439/32685201-2f9fdd9c-c652-11e7-9d7c-77653785bab4.png)

Same result.  I deleted the "thing" and readded but still no low point for humidity.

**Comment by boc-tothefuture** [comment]
New PR in..  Sorry, I am on a roll w/ typos on this one.  :(

**Comment by swamiller** [comment]
Looks good now, thank you!

**Comment by BCS-JonW** [comment]
Ditto... Setpoints look good now.

**Comment by boc-tothefuture** [comment]
ok - sounds like we can close this one for real now @craigham
