### ISSUE TITLE
Missing Omni Updates

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#99]
It appears the omnilink addon is missing updates from the Omni periodically.  I can't detect a pattern, but I noticed that SnapLink will show the correct state and our state in Openhab.  I have only noticed it on lighting.

@craigham are you seeing this too?

**Comment by craigham** [comment]
@boc-tothefuture I can't say I have.  However, I have issues with general stability of openhab 2 while running within a docker container.  This leads to restarts.  So something like this isn't something I would have looked for.

Would you be able to log events within Snaplink, and then could do a comparison?  Also, maybe we could do some extra logging around the connection to see if it is dropping/reestablishing within openhab.

**Comment by BCS-JonW** [comment]
I'm seeing this as well.  However, I've tracked it down to some specific configs that made it repeatable (at least in my setup).

It seems that any UPB switches that I had configured to use the "switch" channel in my sitemap, would operate the device properly, but would not update status.  Seems that the UPB devices only supported the "level" channel and I was improperly trying to use it as a switch.  There were never any errors, it just wouldn't track status.  It's a bit annoying in the BasicUI as using the level command lists 0% or 1% status for simple on/off devices when using the "switch" channel suppresses the percentage display.

{channel="omnilink:upb:home:72:level"} = Proper status tracking
{channel="omnilink:upb:home:72:switch"} = No status tracking

**Comment by swamiller** [comment]
@BCS-JonW I reported this as a different description but similar problem, see #92

**Comment by boc-tothefuture** [comment]
@BCS-JonW - the 'switch' type is used for scene switches.

**Comment by boc-tothefuture** [comment]
I believe this is fixed by the same change that fixed the deadlock issue.  I haven't seen it crop up in a while.
